Public Class CReportService
    Public Function VIEW_LOADING_INTRODUCTION_TM(LOAD_HEADER_NO As String) As DataTable
        Dim Sql As String = "SELECT LOAD_HEADER_NO, SHIPMENT_NO, CARRIER_ID, CARRIER_NAME, DRIVER_NAME, TU_ID, TU_ID1, CANCEL_STATUS, LOAD_STATUS, CREATION_DATE, UPDATE_DATE, SEAL_NUMBER, SEAL_USE, DO_NO, COMPARTMENT_NO, ISLAND_NO, ISLAND_NAME, SALE_PRODUCT_ID, SALE_PRODUCT_NAME, SALE_PRODUCT_CODE, PRODUCT, IS_WEIGHT_PROCESS, STATUS_WEIGHT, IS_WEIGHT, NO_WEIGHT, PRESET, ADVICE, UNIT, PRODUCT_UNIT, CUSTOMER_CODE, CUSTOMER_NAME, SHIP_TO_CODE, SHIPTO, SHIPTO_ADDRESS, PLAN_DATE, SPECIAL_TEXT1, SPECIAL_TEXT2, SPECIAL_TEXT3, SPECIAL_TEXT4 FROM RPT.VIEW_LOADING_INTRODUCTION_TM WHERE LOAD_HEADER_NO=" + LOAD_HEADER_NO
        Dim dt As DataTable = Oradb.ExecuteReader(Sql)
        Return dt
    End Function
    Public Function DAILY_LOADING_DETAIL(LOAD_HEADER_NO As String) As DataTable
        Dim Sql As String = "SELECT LOAD_HEADER_NO, SHIPMENT_NO, SEAL_USE, SEAL_NUMBER, SHIPMENT_REF, TU_CARD_NO, TU_NUMBER, TU_NUMBER1, TU_ID, TU_ID1, VEHICLE_NUMBER, VEHICLE_ID, VEHICLE_MAP_TYPE, DRIVER_NAME, CARRIER_NAME, T_ENTRY, T_BILLING, T_REGISTOR, T_REGISTOR2, T_WEIGHTIN, T_BAY, T_TOPCHECK, T_WEIGHTOUT, T_EXIT, T_QUEUE, T_SHIPMENT, T_SEAL, EOD_DATE, BAYSTART, BAYSTOP, CANCEL_STATUS, LOAD_STATUS, WEIGHT_IN, WEIGHT_OUT, BATCH_NO, DO_NO, COMPARTMENT_NO, ISLAND_NO, ISLAND_NAME, BAY_NO, BAY_NAME, SALE_PRODUCT_ID, SALE_PRODUCT_NAME, SALE_PRODUCT_CODE, BASE_PRODUCT_ID, BASE_PRODUCT_NAME, COMPAMENT_CAPACITY, ADVICE, PRESET, TANK_NAME, METER_NO, TEMP, API60F, DESITY15C, FLOWRATE_AVG, PRESSURE, LOADED_GROSS, LOADED_NET, LOADED_VOLOBS, LOADED_VOL15C, LOADED_VOL30C, LOADED_NET_CAL, TOT_GROSS_START, TOT_GROSS_STOP, TOT_NET_START, TOT_NET_STOP, TOT_VOL30C_START, TOT_VOL30C_STOP, UNIT, VCF15C, VCF30C, LOADED_MASS, T_START, T_STOP, SHIP_TO_CODE, SHIPTO_NAME, CUSTOMER_CODE, CUSTOMER_NAME, GOV_PROJECT, GOV_IS_PRINT, GOV_PRINT_NO FROM RPT.DAILY_LOADING_DETAIL WHERE LOAD_HEADER_NO=" + LOAD_HEADER_NO
        Dim dt As DataTable = Oradb.ExecuteReader(Sql)
        Return dt
    End Function
End Class
