Public Class CReportService
    Public Function VIEW_LOADING_INTRODUCTION_TM(LOAD_HEADER_NO As String) As DataTable
        Dim Sql As String = "SELECT LOAD_HEADER_NO, SHIPMENT_NO, CARRIER_ID, CARRIER_NAME, DRIVER_NAME, TU_ID, TU_ID1, CANCEL_STATUS, LOAD_STATUS, CREATION_DATE, UPDATE_DATE, SEAL_NUMBER, SEAL_USE, DO_NO, COMPARTMENT_NO, ISLAND_NO, ISLAND_NAME, SALE_PRODUCT_ID, SALE_PRODUCT_NAME, SALE_PRODUCT_CODE, PRODUCT, IS_WEIGHT_PROCESS, STATUS_WEIGHT, IS_WEIGHT, NO_WEIGHT, PRESET, ADVICE, UNIT, PRODUCT_UNIT, CUSTOMER_CODE, CUSTOMER_NAME, SHIP_TO_CODE, SHIPTO, SHIPTO_ADDRESS, PLAN_DATE, SPECIAL_TEXT1, SPECIAL_TEXT2, SPECIAL_TEXT3, SPECIAL_TEXT4
                             FROM RPT.VIEW_LOADING_INTRODUCTION_TM WHERE LOAD_HEADER_NO=" + LOAD_HEADER_NO
        Dim dt As DataTable = Oradb.ExecuteReader(Sql)
        Return dt
    End Function

End Class
